version: '3'

services:
  hall_of_rock_db:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hall_of_rock
    volumes:
      - "hall_of_rock-db:/var/lib/postgresql/data"
volumes:
  hall_of_rock-db: